### PR TITLE
Added separate root password (SSH) with new config flag and configuration.

### PR DESCRIPTION
**Pull request by Schm1tz1**
- SSH_PASSWORD -> /etc/passwd/ and /etc/shadow checked, ok!
- default password set in config and added in check_conf.sh!
- Import/Export of configs ok!
- Load/Save-Functions in Configurations have been tested, SSH_PASSWORD in system.conf is set correctly and SSH password for root user is changed after reboot.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
.

**Comment by Schm1tz1** [comment]
Thanks. Rather straightforward, just needed to find out how config handling is done and where changes can be applied.
Implementation: 30 minutes, trying to fix a bug that was a PEBKAC: 3 hours...
Make sure you reset your browser cache so you are not using a cached version of the Javascript file... Have fun!

**Comment by Catfriend1** [comment]
It woule be cool if we could add a cache buster behind .js?cachebuster=somerandomnumber

My phone didn't show the ftp settings for weeks because of caching and I deleted cache now and it immediately worked.

**Comment by Schm1tz1** [comment]
I have something similar in my smart home to force refreshing of a preview of  IP camera images every few seconds. Adding the Unix timestamp should do it. I can add it to the pull request if you like. Might be tomorrow or Monday though.

**Comment by Schm1tz1** [comment]
@Catfriend1 sorry for pushing to master - forgot to select my testing branch by accident. Maybe we should close this pull request if the ROOT password stuff is ok and tested by you and open a new issue/fork for the cache buster. There might be some alignment necessary on what is the best way to proceed.

**Comment by Catfriend1** [comment]
Yes, maybe a new PR is better to add the cache buster. I'm not sure when I get to reflash my camera. @roleoroleo do we require a real life test on a camera for him to merge the PR?

**Comment by roleoroleo** [comment]
I'm testing it on my cam.
I need a few days to merge it.

**Comment by roleoroleo** [comment]
The PR is ok.
I tested it with ssh, ftp and scp.
Only a detail: if you want to set "default empty" the file etc/system.conf must be
`SSH_PASSWORD=`
and not
`SSH_PASSWORD=root`
And same thing for the file script/check_conf.sh

**Comment by Schm1tz1** [comment]
Sure, good point about the thousands of issued. In general one shouldn't set a default PW to empty. Lots of users will never change it or even think about setting a secure password but maybe one can lead users there and pop up a reminder as a future feature. I will change the default PW and commit.

**Pull request merged**
