### PR TITLE
ftppush: Allow specifying target directory (fixes #101)

### LINKED ISSUE #101: FTP upload - sub directory option
Hi
Would it be easy to add an option to choose a subfolder for ftp upload as at the moment it's only to the root.

Cheers

### PR DESCRIPTION
**Pull request by Catfriend1**
- ftppush: Allow specifying target directory (fixes #101)
- Create target dir if it does not exist

Verified working on my device.

### CODE REVIEW

**Comment by roleoroleo** [comment]
I have a little problem.
If the folder doesn't exist the script doesn't create it.
I tried directly with nc command and it doesn't work.
If I create the folder manually it works.
I'm using a ProFTP server.

**Comment by Catfriend1** [comment]
Ok, thanks for the feedback. I'll get back to this in a few days and test with proftpd, hopefully to update the pr so it works correctly. I've previously tested on vsftpd.

**Comment by Catfriend1** [comment]
@roleoroleo  Good catch! I've corrected it to work on both vsftpd and proftpd. The line ending \r\n works with both, \n only with vsftpd. I've also added "-q 5" to ensure the command will terminate in case of a connection or protocol error and not hang execution forever.

vsftpd:
```
220 (vsFTPd 3.0.3)
331 Please specify the password.
230 Login successful.
257 "/test4" created
221 Goodbye.
```

proftpd:
```
220 ProFTPD Server (Debian) [127.0.0.1]
331 Password required for ftpuser
230 User ftpuser logged in
257 "/test3" - Directory successfully created
221 Goodbye.
```

**Comment by roleoroleo** [comment]
I have another problem:
```
nc: unrecognized option: q
BusyBox v1.32.0.git (2020-08-19 16:15:08 CEST) multi-call binary.

Usage: nc [-iN] [-wN] [-l] [-p PORT] [-f FILE|IPADDR PORT] [-e PROG]

Open a pipe to IP:PORT or FILE

        -l      Listen mode, for inbound connects
                (use -ll with -e for persistent server)
        -p PORT Local port
        -w SEC  Connect timeout
        -i SEC  Delay interval for lines sent
        -f FILE Use file (ala /dev/ttyS0) instead of network
        -e PROG Run PROG after connect
```

**Comment by Catfriend1** [comment]
@roleoroleo Ok, let's use -w then. It's roughly the same as the -q timeout on debian's nc. I just want to be sure in case it cannot connect the code will move on and not get stuck :-).

**Pull request merged**
