### PR TITLE
Play video from web interface

### PR DESCRIPTION
**Pull request by BenjaminFaal**
Instead of always having to download a video now you can play it directly from the web interface.

### CODE REVIEW

**Comment by BenjaminFaal** [comment]
@roleoroleo what do you think of this?

**Comment by roleoroleo** [comment]
I will try it next monday.
Thank you for your contribution.

**Comment by BenjaminFaal** [comment]
@roleoroleo

**Comment by roleoroleo** [comment]
@BenjaminFaal 
Thank you for your work.

**Pull request merged**
