### PR TITLE
Added WiFi Strength in status page

### PR DESCRIPTION
**Pull request by elraro**
Related to issue #129

This PR adds visually the quality of the received wifi signal.

captura

### CODE REVIEW

**Comment by roleoroleo** [comment]
I have a strange beahvior.
When the cam is near to the router the signal strength is > 100:
immagine

**Comment by elraro** [comment]
Is it a Allwinner cam?

Can you paste the output of /proc/net/wireless ?
imagen

In my cam (Allwinner) max link value is 70

**Comment by roleoroleo** [comment]
Yes.
immagine

**Comment by elraro** [comment]
imagen

https://www.cyberciti.biz/tips/linux-find-out-wireless-network-speed-signal-strength.html

How can we see the driver/device of wlan?

**Comment by roleoroleo** [comment]
Sorry, my mistake.
I have a wrong version of status.js file.
Probably I edited it manually on the cam.

**Pull request merged**
