### PR TITLE
Add MQTT Advertise

### PR DESCRIPTION
**Pull request by EnricoFerro**
This is the porting of the project https://github.com/EnricoFerro/yi-hack-to-mqtt as descripted in #181.

This allow to make advertise for the status page and configuration page on MQTT.
This also allow to generate a YI Hack Device using [MQTT Discovery](https://www.home-assistant.io/docs/mqtt/discovery/) in home assistant.

Of this project esists a stand-alone version on https://github.com/EnricoFerro/yi-hack-to-mqtt-script useful for the old release of the hacking.

### CODE REVIEW

**Comment by roleoroleo** [comment]
Thank you for your code.
I need some time to try it...

**Comment by roleoroleo** [comment]
Great work, thank you very much for the contribution.
I tested it but I'm not an home assistant expert...
So I didn't check the ha part in depth.
I have 2 notes to share with you:
- You didn't add a link in the main web site (i.e. mqtt page), so the user needs to know the page mqtt_adv.
- The crontab daemon doesn't start if not configured by the user.

But no problem, I will fix these problem after the merge.
If you agree I will also add your work to mstar and allwinner-v2 project.

I'm working on another mqtt project to configure all parms of the cam.
Something like PREFIX/CONFIG_FILE/PARAMETER
But I think it's not a problem, maybe a partial overlap.

**Comment by EnricoFerro** [comment]
Hi,

Yes, I've need to add the link in main page. Honestly I've no idea where to put the link, if in the main menù or as link in mqtt page.

I forgot ( never see ) the crontab startup... ..should be changed the startup.sh for check the cron job and start if needed....

For merge the project on mstar and allwinner-v2 project, it is a good idea. I've not have these camera so I've never checked but don't see any problem, ( it work using mqttv4.conf / mosquitto and shell ).

The logic of this modify is to use all the existing scripts like `www/cgi-bin/camera_settings.sh` or `www/cgi-bin/links.sh` and return the result in a mqtt path, keep all more "_simple_" as possible. I splitted only the information in system page because create a lot of spam in Home Assistant database ( Example: the IP never change between a boot and another ).
The Home Assistant script is only a describer of the information in MQTT topic. So it is possible to change the topic of the MQTT for the future development.

My  next idea is to develop  a homie solution that is similar as MQTT PREFIX/CONFIG_FILE/PARAMETER, and also add some command like $MQTT_PREFIX/reboot or $MQTT_PREFIX/update. The real problem is to create a valid ( not a shell script ) mqtt listener inside the camera.

**Comment by roleoroleo** [comment]
> My next idea is to develop a homie solution that is similar as MQTT PREFIX/CONFIG_FILE/PARAMETER, and also add some command like $MQTT_PREFIX/reboot or $MQTT_PREFIX/update. The real problem is to create a valid ( not a shell script ) mqtt listener inside the camera and to manage the modify of the configuration sending the MQTT information ( For example in camera_setting page ).

Check this commit: https://github.com/roleoroleo/yi-hack-Allwinner/commit/9ba4a7ac87f0349a7bc1cc79541fa4f04a8862be

**Pull request merged**
