### PR TITLE
ftppush.sh: Automatically move recordings from sdcard to FTP storage

### PR DESCRIPTION
**Pull request by Catfriend1**
Purpose:
- Automatically move recordings from sdcard to FTP storage

Prerequisites:
1. Set camera settings through the Yi-Hack web interface and reboot the camera.
- DISABLE_CLOUD=yes
- RECORD_WITHOUT_CLOUD=yes

2. You need an already set-up and working FTP server. E.g. vsftpd

Configuration:
Edit "ftppush.sh" and upload it to "/home/yi-hack/script/ftppush.sh". Don't forget to run "chmod 0755 /home/yi-hack/script/ftppush.sh" via SSH.
Ensure you use the "/home/yi-hack/script/system.sh" file from this PR.
- Function "uploadToFtp": fill in variables FTP_HOST, FTP_USERNAME and FTP_PASSWORD

Reboot the camera, the script will work backgrounded and upload new recordings to the FTP server. If the upload succeeded, the recorded files will be deleted from the sdcard.

Testing:
- Verified working with my Yi Home 1080p v3 camera using a Samsung SDXC 64 GB SDcard (formatted FAT32 with 4K block size)
- Used a Debian buster 10.4 server running vsftpd on port 21.

### CODE REVIEW

**Comment by Catfriend1** [comment]
While this is already working great on my camera, it's still not ready to be merged yet.

ToDo:
- Make the three FTP variables configurable on the Yi-Hack web interface.
- Add an option to the web interface: "[x] Upload recordings to FTP server and delete them after successful upload", this needs to be honored by "system.sh"

**Comment by roleoroleo** [comment]
Do you think you will also make changes to the web part and to system.sh in this pr?

**Comment by Catfriend1** [comment]
Not sure yet. I'm currently running production with the scripts and then deciding in 2 weeks if I keep or ditch the YiCam. YiCam annoys me much because of the constant tree-in-the-wind recording with alarms I need to analyze myself before forwarding via push if it contains real *intruder* motion.

Is it difficult to make the web ui part?

**Comment by Catfriend1** [comment]
So I hacked up a little UI via WinSCP, but at first glance it was hard to edit those .gz archives real time. But deobfuscating the js works fine to edit it.

**Comment by roleoroleo** [comment]
Normally I edit js files on the dev machine and I run compile.www without rebuild all the hack.
The compressed archive is then available in _install directory.

**Comment by Catfriend1** [comment]
Ok, thanks for the pointer. Is there anything more todo before preview? I'm running the ftp pr since morning and it works for my camera.

**Pull request merged**
